# Site
name: Artificial Intelligence
title: Disruptive Technologies
description: Artificial Intelligence as a game changer in various industries.
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mms142-groupg-2020
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Marc:
    name: Marc Eduard Lagayan
    display_name: Marc Eduard
    gravatar: d4b5b04d229c9b2ce68c69332da2ab59
    email: mclagayan@up.edu.ph
    web: https://github.com/mclag
    twitter: 
    description: UPOU BAMS Student
  Lea Lyn:
    name: Lea Lyn Latawan
    display_name: Lea Lyn Latawan   
    gravatar: b8b690c5c2c5fef4ad8f3a697a63a5df
    email: lmlatawan@up.edu.ph
    web:  https://github.com/lealynfs
    twitter:
    description: UPOU BAMS Student
  Janella Rayne:
    name: Janella Rayne Habal
    display_name: Janella Rayne Habal
    gravatar: ff2f2c71ce5f332b16903b503f346bbc
    email: jrhabal@up.edu.ph
    web:  https://github.com/jalaulan
    twitter:
    description: UPOU BAMS Student
  Mia:
    name: Mia Angela Jaro
    display_name: Mia Angela Jaro
    gravatar: 11e3c3a50db340f25218829e5f086e45
    email: mcjaro@up.edu.ph
    web:  https://github.com/sleepingmeow
    twitter:
    description: UPOU BAMS Student 
 Adrian:
    name: Adrian Colin Hilario
    display_name: Adrian Colin Hilario
    gravatar: 2b4f6a0008726696321cbb90aa09610c
    email: achilario@up.edu.ph
    web: https://github.com/IanHilario
    twitter: 
    description: UPOU BAMS Student
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
